server:
  port: 8848
  servlet:
    context-path: /api
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 600000
      max-lifetime: 28740000
      auto-commit: true
      pool-name: NoteCP
      connection-test-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/note?serverTimezone=UTC&autoReconnect=true
    username: dev
    password: 1234
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-idle: 300
          max-active: 8000
          max-wait: 500
      password: 123
mybatis:
  type-aliases-package: com.cspup.notespro.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
#    在控制台打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  file:
#    path: E://logs/log.log